# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planner', models.CharField(max_length=60)),
                ('destination', models.CharField(max_length=100)),
                ('start', models.TextField()),
                ('end', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='buddies',
            field=models.ManyToManyField(related_name='buddies', to='travel_buddy_app.User'),
        ),
    ]
